language: php
php:
  - 7.2
  - 7.3
  - 7.4

install: composer install
script:
  - ./vendor/bin/phpunit --configuration tests/FullTests.xml --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 src/

after_script: php vendor/bin/coveralls
